-- Fresh installations only. No seeded login credentials.
CREATE TABLE IF NOT EXISTS t_user (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(200) NOT NULL, real_name VARCHAR(50), email VARCHAR(100),
 phone VARCHAR(20), avatar VARCHAR(500), role VARCHAR(20) DEFAULT 'seeker',
 status TINYINT NOT NULL DEFAULT 1, deleted TINYINT NOT NULL DEFAULT 0,
 last_login_time DATETIME, create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
 update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
